version: '3.8'

services:

  postgres:
    image: postgres:15
    container_name: keycloak-postgres
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "keycloak"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - keycloak-network

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin123
      KC_HOSTNAME_STRICT: "false"
      KC_HOSTNAME_STRICT_HTTPS: "false"
      KC_HTTPS_REQUIRED: "none"
      KC_PROXY: edge
      KC_HTTP_ENABLED: "false"
      KC_HTTPS_CERTIFICATE_FILE: ""
      KC_HTTPS_CERTIFICATE_KEY_FILE: ""
      KC_HTTPS_TRUST_STORE_FILE: "/etc/x509/https/tls.crt"
      KC_HTTPS_TRUST_STORE_PASSWORD: "password"
      KC_PROXY_ADDRESS_FORWARDING: "true"
      KC_HTTPS_REQUIRED: "external"
    command:
      - start-dev
    ports:
      - "8888:8080"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./certs:/etc/x509/https
    networks:
      - keycloak-network


volumes:
  postgres_data:
    name: keycloak_postgres_data

networks:
  keycloak-network:
    name: keycloak-network
